### ISSUE TITLE
Rs485 2 wire

### ISSUE THREAD

**Issue by phoenix-blue** [solmoller/eversolar-monitor#44]
Hi,

Not really an issue but an question. 
Is it possible to use an 2 wire RS485 connection in place of an 4 wire RS485 connection?

**Comment by kiekerjan** [comment]
Yes, this is possible. You need to connect pins 1 and 3 on the inverter to TX on your wire rs485 connector and pins 2 and 6 to RX. In case the inverter replies with something like

`**95 55 ff ff ff** df f7 ff fd d7 00 95 55 ff ff ff df
ff ff fd df 00`

that is, ff instead of 00, the polarity is inverted and you should switch tx and rx. See also here https://github.com/solmoller/eversolar-monitor/blob/wiki/Hardware.md
